CMakeLists.txt: set(CMAKE_CXX_STANDARD 11).
If "make" fails without manually specifying the C++11 flag, it
should be considered a bug, end-users shouldn't be expected to
supply any manual compiler flag. In this case, openEMS should have
"set(CMAKE_CXX_STANDARD 11)" in CMakeFiles.txt. Note that the flag
CMAKE_CXX_STANDARD is introduced in CMake 3.1, not CMake 3.0, we
bump the minimum CMake version accordingly. Since CMake 3.5 is
available even on Ubuntu 14.04, compatibility issues are unlikely.

Beware that after this commit, manually setting "std=c++11" may
cause compile failure if an older GCC version (e.g. GCC 4.8/5/6)
is used:

    /usr/include/boost/math/constants/constants.hpp: In static member
    function 'static constexpr T boost::math::constants::detail::constant_half<T>
    ::get(const mpl_::int_<5>&)':
    /usr/include/boost/math/constants/constants.hpp:252:3: error: unable to
    find numeric literal operator 'operator"" Q'
       BOOST_DEFINE_MATH_CONSTANT(half, 5.000000000000000000000000000000000000e-01, "5.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e-01")

This is a known Boost/GCC issue. According to [1], because CMake
is adding "-std=gnu++11" (following "set(CMAKE_CXX_STANDARD 11)"),
while the user is also manually setting "std=c++11" in "CXXFLAGS",
GCC is put into an inconsistent state. As a result, Boost believed
"__float128" support is turned on when it's actually not.

Thus, after this commit, passing "-std=c++11" is not just useless,
but is harmful. The documentation should be updated to instruct users
not to pass "-std=c++11" after this commit.

[1] https://github.com/boostorg/math/issues/272

Signed-off-by: Yifeng Li <tomli@tomli.me>