FDTD: remove "using namespace std" from global headers
In general, it's not recommended to write "using namespace std"
in a header file, because it causes accidental namespace pollution
to all files that use this header indirectly. In openEMS, the
statement "using namespace std" was written into "tools/ExpenseLog.h",
which was then indirectly included to nearly all engines and all
extensions, which violates the principle of least surprises.

When building openEMS with MSVC, this unintentional namespace
pollution also causes a name conflict between std::byte in C++17 and
"C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\shared\rpcndr.h",
creating hundreds of build errors.

    C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\shared\rpcndr.h(203): error C2872: 'byte': ambiguous symbol
    C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\shared\rpcndr.h(202): note: could be 'unsigned char byte'
    C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.50.35717\include\cstddef(34): note: or       'std::byte'

Since unintentional namespace pollution is both a theoretical and
practical problem, this commit removes "using namespace std" from
"tools/ExpenseLog.h", usage of most STL classes in openEMS are now
made explicit using the "std::" prefix.

If a line is exceedingly long (most modified lines were already extremely
long even before adding the "std::" prefix), this commit also uses this
opportunity to break them into multiple lines for readability.

As a special case, "using std::out; using std::cerr; using std::endl"
are imported into the global namespace in some ".cpp" files to reduce
the length of repetitive string formatting code.

Signed-off-by: Yifeng Li <tomli@tomli.me>