openems.cpp: fix argument parsing with multiple openEMS() instances
If different openEMS() instance is created in Python to run multiple
simulations, with different command-line options, the following error
occurs:

Traceback (most recent call last):
  File "openEMS/openEMS.pyx", line 534, in openEMS.openEMS.openEMS.Run
  File "openEMS/openEMS.pyx", line 495, in openEMS.openEMS.openEMS._SetLibraryArguments
RuntimeError: option '--numThreads=0' is ambiguous and matches different versions of '--numThreads'

The reason is simple. The command-line arguments are tracked by global.h
throughout the lifetime of the entire openEMS shared library, regardless
of how many instances of openEMS() are created. When multiple openEMS()
instances are used, the available global options are added multiple times,
making each option a conflict because of multiple candidates.

This commit changes openEMS::collectCommandLineArguments() so that
we always call clearOptionDesc() to clear and then readd all available
options just before we start parsing arguments. This way, the callback
handlers are always reinstalled to the current openEMS() instance.

Note that this fix is incomplete. Historically, openEMS was written as a
standalone program, so there are other problems when running multiple
openEMS() instances. Additional Refactoring is eventually needed.

See: https://github.com/thliebig/openEMS/issues/187

Signed-off-by: Yifeng Li <tomli@tomli.me>