python/setup.py: drop minimum version requirements, close #165.
On Debian 11, running openEMS via Python produces the following
error:

    ImportError: numpy.core.multiarray failed to import

This is a binary compatibility problem that should've never happened.
But it did. Why? Because setup.py requires NumPy 1.26, but Debian only
has NumPy 1.24. Python finds no system package that can satisfy this
requirement so download binaries that from PyPI instead. But now we have
NumPy v2 incompatible with the rest of the system, creating the binary
compatibility problem. It's exactly why PyPI packages should never be
mixed outside a virtualenv. Same problems exist for h5py and cython as
well. although there's no compatibility problem per se, at least, not
yet.

These version requirements were introduced by in commit 5bc31d0 ("add
missing package python dependencies") and e7620dc ("also add cython
(everything but setuptools)"), but no justification was given about why
these minimum versions were necessary. If I recall correctly, openEMS
used to be compatible even with very ancient Python versions.

For now, drop these version requirements entirely. It's a bit sloppy
but it's easier than trying to test ancient systems and figuring out
the exact minimum versions. If we insist on adding version requirements
in the future, it should be at least compatible with Debian's oldstable.

Signed-off-by: Yifeng Li <tomli@tomli.me>