tools/array_ops.h: use GCC extension for clang-cl
When compiling openEMS using Visual Studio with clang-cl,
the following error occurs:

    openEMS/tools/array_ops.h(50,15): error: overloaded 'operator+'
    must have at least one parameter of class or enumeration type
       50 | inline __m128 operator + (__m128 a, __m128 b) {return _mm_add_ps(a, b);}
          |               ^

The same error also repeats for "operator-", "operator*", "operator/",
"operator+=", "operator-=", "operator*=", "operator/=".

Since it's clang-cl, the simplest fix is to use the GCC extension
codebase instead. When "clang" is running under "clang-cl" mode
(which is a MSVC-compatibility mode), the macro __GCC__ is not set,
but the macro __clang__ is.

This commit enables the GCC vector extension codepath for both
GCC and clang to fix the build.

Signed-off-by: Yifeng Li <tomli@tomli.me>